spring.application.name=core-service
spring.datasource.url=jdbc:postgresql://localhost:5432/StepIA
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

server.port=8081
